import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@email.com',
      password: bcrypt.hashSync('123123123'),
      isAdmin: true,
    },
    {
      name: 'Michael',
      email: 'user@email.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 89,
      brand: 'Nike-User',
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Great shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Sweet Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 96,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 2,
      description: 'A popular shirt for men',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Thin Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 190,
      brand: 'Ndure',
      rating: 5,
      numReviews: 3,
      countInStock: 5,
      description: 'A popular shirt for girls',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 3.9,
      numReviews: 13,
      countInStock: 8,
      description: 'Smart looking shirt',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Outfitter',
      rating: 4.5,
      numReviews: 7,
      countInStock: 9,
      description: 'pants',
    },
    {
      name: 'Classic Touser',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 25,
      brand: 'Casely',
      rating: 3.4,
      numReviews: 14,
      countInStock: 10,
      description: 'A popular pants',
    },
  ],
};

export default data;
